### ISSUE TITLE
README.md missing references

### ISSUE THREAD

**Issue by curiousleo** [aspiwack/peppermint-prover#14]
The `README.md` looks like it's meant to link to interesting-sounding references, but the links are sadly missing.

![Screenshot_2020-11-10 aspiwack peppermint-prover](https://user-images.githubusercontent.com/697092/98698254-204d9300-2376-11eb-9ce0-6d86c62c7684.png)

**Comment by aspiwack** [comment]
Hi @curiousleo,

I've got to admit: I noticed this a while ago (though I still don't
know how it could have happened). I haven't revisited the README in a
while, it's awfully outdated, as I'm currently going a completely
different direction than what I wrote about there.

That being said, it is no excuse for a lack of good bibliographical
references. Hopefully I'll remember, myself, what all of these
references were about.

If it's not done in a week, please yell.
